// solidjs/solidjs-1/src/App.tsx
import { createEffect, type Component } from 'solid-js';

import logo from './logo.svg';
import styles from './App.module.css';
import { render } from '@engagespot/client';

const App: Component = () => {
   const apiKey = import.meta.env.VITE_ENGAGESPOT_API_KEY;

   // this is for testing purposes
   // write code to get your app users unique identifier instead
   const userId = import.meta.env.VITE_ENGAGESPOT_USER_ID;

   createEffect(() => {
      render('#bellIcon', {
         apiKey,
         userId,
      });
   });

   return (
      <div class={styles.App}>
         <div class={styles.container}>
            <span>Get started with Engagespot</span>
            <div id='bellIcon'> </div>
         </div>

         <header class={styles.header}>
            <img src={logo} class={styles.logo} alt='logo' />
         </header>
      </div>
   );
};

export default App;

// react/cra/react-17/src/App.js
import logo from './logo.svg';
import './App.css';
import { Engagespot } from '@engagespot/react-component';

function App() {
   const apiKey = process.env.REACT_APP_ENGAGESPOT_API_KEY;

   // this is for testing purposes
   // write code to get your app users unique identifier instead
   const userId = process.env.REACT_APP_ENGAGESPOT_USER_ID;

   return (
      <div className='App'>
         <header className='App-header'>
            <div className='engagespot-container'>
               {apiKey && userId && <Engagespot apiKey={apiKey} userId={userId} />}
            </div>

            <img src={logo} className='App-logo' alt='logo' />

            <p>
               Edit <code>src/App.js</code> and save to reload.
            </p>

            <a
               className='App-link'
               href='https://reactjs.org'
               target='_blank'
               rel='noopener noreferrer'
            >
               Learn React
            </a>
         </header>
      </div>
   );
}

export default App;
